name: RomaStore
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+23

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^4.4.2

  # BASE
  intl: 0.17.0

  # FIREBASE PACKAGES
#  firebase_crashlytics: ^2.1.1
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1

  # UI
  flutter_vector_icons: ^1.0.0
  dotted_border: ^2.0.0
  flutter_rating_bar: ^4.0.0
  otp_text_field: ^1.1.3
  flutter_staggered_grid_view: ^0.4.0
  country_code_picker: ^2.0.2
  html: ^0.15.0
  flutter_html:
  package_info: ^2.0.2

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.1.0

  # STATE MANAGEMENT
  provider: ^6.0.2
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  # ADS
  #google_mobile_ads: ^0.13.2

  # IMAGES
  image_picker: ^0.8.2
  cached_network_image: ^3.1.0
  photo_view: ^0.13.0
  flutter_math_fork:
  flutter_svg:
#wakelock: ^0.6.1+2
  wakelock_web: ^0.4.0
  video_player_web: ^2.0.8
  video_player: ^2.4.0

  # AUTHENTICATION
  google_sign_in: ^5.0.4
  the_apple_sign_in: ^1.1.1

  # CONNECTIVITY
  http: ^0.13.3
  connectivity: ^3.0.6
  share: ^2.0.4

  #TOOLS
  google_fonts: ^2.1.0

  # WEB TOOLS
  webview_flutter: ^2.0.10

  # PAYMENTS
  razorpay_flutter: ^1.2.7
  #flutter_pay: ^1.0.1

  # LAUNCH URL
  url_launcher: 6.0.3

  flutter_localizations:
    sdk: flutter
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.3
  flutter_native_splash: ^2.1.6
flutter_native_splash:
  color: "#FFFFFF"
  image: images/mySplash.png

  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher-playstore.png"
  adaptive_icon_background: "assets/ic_launcher-playstore.png"
  adaptive_icon_foreground: "assets/rounded.png"
  remove_alpha_ios: true
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  #flutter pub run flutter_launcher_icons:main
  #flutter pub run flutter_native_splash:create

flutter:

  uses-material-design: true

  assets:
    - images/
    - lang/
    - assets/